# Discord Bot Configuration
# To get your Discord bot token:
# 1. Go to Discord Developer Portal (https://discord.com/developers/applications)
# 2. Click "New Application" and give it a name
# 3. Go to the "Bot" section in the left sidebar
# 4. Click "Add Bot" if you haven't created a bot yet
# 5. Under the bot's username, click "Reset Token" and copy the new token
# 6. Paste your token below (keep it secret!)
discord_token: discord_bot_token

# OpenAI API (for embeddings)
# To get your OpenAI API key:
# 1. Go to OpenAI's website (https://platform.openai.com)
# 2. Sign in or create an account
# 3. Click on your profile icon and select "View API keys"
# 4. Click "Create new secret key"
# 5. Copy your API key (you won't be able to see it again!)
# 6. Paste your key below (keep it secret!)
openai_api_key: openai_api_key
embedding_model: "openai" # Options: "openai", "huggingface"
outies:
# To get your Discord admin user ID:
# 1. Go to Discord and go to User Settings (gear icon)
# 2. Go to App Settings > Advanced
# 3. Enable "Developer Mode"
# 4. Right-click on your username
# 5. Click "Copy ID"
  - outie_id: outie_user_id
    topics:
      - name: "Name of the topic"
        role: |
          This is the full description of the role for the bot to play during the conversation.
          This is the "system prompt" that will be used to set the context for the bot.
# Path to the directory containing the documents to be processed
        docs_dir: "./data/documents"
        channels:
# To get your Discord server (guild) ID:
# 1. Open Discord and go to User Settings (gear icon)
# 2. Go to App Settings > Advanced
# 3. Enable "Developer Mode"
# 4. Right-click on your server name
# 5. Click "Copy Server ID"
# 6. Paste the ID below
          - guild_id: discord_server_id
# To get your Discord channel ID:
# 1. Open Discord and go to the channel you want to use
# 2. Right-click on the channel name
# 3. Click "Copy ID"
# 4. Paste the ID below
            channel_id: discord_channel_id
      - name: "Name of the topic"
        role: |
          System prompt for the bot to play during the conversation.
        docs_dir: "./data/documents2"
        channels:
          - guild_id: discord_server_id
            channel_id: discord_channel_id